### ISSUE TITLE
Add exact term search

### ISSUE THREAD

**Issue by ranajaydas** [za-grad/otvoreni-akti#11]
For example, if I search for:
```bash
"Zagreb Park"
```
it should only show results for that exact term

**Comment by metakermit** [comment]
That would be sweet. I didn't ask for this cause I don't know how difficult it would be, but I'm sure it would be helpful in lots of cases.

**Comment by ranajaydas** [comment]
It should be possible if we can change the act_analyzer on the fly. This is what it currently looks like:
```bash
act_analyzer = analyzer(
    'act_analyzer',
    tokenizer=tokenizer('standard'),
    filter=['lowercase', 'snowball']
)
```

Its possible if we have an ability to choose a different anaylzer based on if user has input the text between "quotes".

**Comment by ranajaydas** [comment]
Actually its a completely different implementation using:
```bash
exact_query = Q('query_string', query=exact_search_term, fields=['content', 'title'])
```
I'm working out the bugs now!
