### ISSUE TITLE
simplify the folder structure

### ISSUE THREAD

**Issue by metakermit** [za-grad/otvoreni-akti#28]
Let's try and create a simpler folder structure based on something like this:

https://github.com/metakermit/hellodjangorest

Also, I think we could rename the project itself from skupstina to otvoreni-akti. Then we could keep the name skupstina just for the Django app. That way in the future in theory we could have another Django app that deals with some other open data (just hypothetically, not saying we really will do this), like I don't know the data about companies in Zagreb and their public finance.

We could then have:

otvoreni-akti/ <- the root git repository

  - .gitignore
  - .env
  - manage.py
  - otvoreni-akti/ <- the Django root package

    - __init__.py
    - settings.py
    - wsgi.py
    - apps/
      - skupstina/

        - views.py
        - models.py

**Comment by metakermit** [comment]
I just realised that the name "skupstina" is kind of misleading BTW. If we can also rename the Django app "skupstina" to "acts" that would probably be a bit more logical.

The explanation was that originally the project was supposed to be scraping both the mayor's acts and the acts of the Zagreb's city council ("Gradska skupština"). Since then the existing search engine of the Skupština got a bit better, so we decided to re-focus only on the mayor's acts.

**Comment by ranajaydas** [comment]
How about we name skupstina to **search**? That's essentially what we have right now in the apps folder - one app to scrape and another to search.

**Comment by metakermit** [comment]
Sounds good. I'd argue that they should both be part of the same Django app, though, cause they deal with the same Django models. One without the other doesn't really make much sense. They can be two separate Python modules within the same Django app, though. The name search for both of them is ok.
