### ISSUE TITLE
Repair styling issues

### ISSUE THREAD

**Issue by mzugcic** [za-grad/otvoreni-akti#55]
Issues as listed by @ranajaydas:

1. It’d look nicer if the edges aligned with the main search bar (the period one is a bit to the left)
2. In mobile view, the boxes shrink a bit so the height isn’t the same as the search box so it looks a bit strange
3. We should add outline: none; to all the search boxes to remove the outlines that occur on selection
4. The additional search info drop down would look better if it’s inside the purple header to maintain visual consistency

**Comment by ranajaydas** [comment]
Done 1, 2 and 4. For 3, outline removed only for the search bar and left for the rest to aid users who do not use a mouse.
